Remove nix-linter from pre-commit hooks
It is unmaintained and has been removed from pre-commit-hooks.nix:
```
error: The option `hooks.nix-linter.entry' is used but not defined.
```